/* empty css                      */import{a as R,S as $,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const q="50818292-28c953def5feac0614fc2706b",E="https://pixabay.com/api/";async function p(s,t=1){const o=new URLSearchParams({key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}),{data:i}=await R.get(`${E}?${o}`);return i}const f=document.querySelector(".gallery"),h=document.querySelector(".load-more-btn"),m=document.querySelector(".loader"),B=new $(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const t=s.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
               <ul class="info">
<li class="photo-info">👍 <span class="span">${o.likes}</span></li>
<li class="photo-info">👁 <span class="span">${o.views}</span></li>
<li class="photo-info">💬 <span class="span">${o.comments}</span></li>
<li class="photo-info">⬇️ <span class="span">${o.downloads}</span></li>
</ul>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){f.innerHTML=""}function y(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function w(){h.classList.remove("hidden")}function u(){h.classList.add("hidden")}const b=document.querySelector(".form"),O=document.querySelector(".load-more-btn"),l=b.elements["search-text"],v=15;let c="",n=1,S=0;b.addEventListener("submit",async s=>{if(s.preventDefault(),c=l.value.trim(),!c){a.warning({title:"Warning",message:"Enter a search term",position:"topRight"}),l.value="";return}n=1,M(),u(),y();try{const t=await p(c,n);if(S=t.totalHits,t.hits.length===0){a.error({title:"Error",message:"Failed to load images",position:"topRight"}),l.select();return}g(t.hits),l.value="",t.hits.length<v?(a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),u()):w()}catch{a.error({title:"Error",message:"Something went wrong",position:"topRight"})}finally{L()}});O.addEventListener("click",async()=>{n+=1,u(),y();try{const s=await p(c,n);g(s.hits);const{height:t}=document.querySelector(".gallery .gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),n*v>=S?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):w()}catch{a.error({title:"Error",message:"Something went wrong",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
