/* empty css                      */import{a as E,S as R,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const $="50818292-28c953def5feac0614fc2706b",q="https://pixabay.com/api/";async function h(o,t=1){const r=new URLSearchParams({key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}),{data:i}=await E.get(`${q}?${r}`);return i}const m=document.querySelector(".gallery"),g=document.querySelector(".load-more-btn"),y=document.querySelector(".loader"),B=new R(".gallery a",{captionsData:"alt",captionDelay:250});function L(o){const t=o.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" />
      </a>
               <ul class="info">
<li class="photo-info">👍 <span class="span">${r.likes}</span></li>
<li class="photo-info">👁 <span class="span">${r.views}</span></li>
<li class="photo-info">💬 <span class="span">${r.comments}</span></li>
<li class="photo-info">⬇️ <span class="span">${r.downloads}</span></li>
</ul>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){m.innerHTML=""}function w(){y.classList.remove("hidden")}function b(){y.classList.add("hidden")}function v(){g.classList.remove("hidden")}function f(){g.classList.add("hidden")}const S=document.querySelector(".form"),H=document.querySelector(".load-more-btn"),l=S.elements["search-text"],p=15;let c="",a=1,u=0;S.addEventListener("submit",async o=>{if(o.preventDefault(),c=l.value.trim(),!c){n.warning({title:"Warning",message:"Enter a search term",position:"topRight"}),l.value="";return}a=1,M(),f(),w();try{const t=await h(c,a);if(u=t.totalHits,t.hits.length===0){n.error({title:"Error",message:"Failed to load images",position:"topRight"}),l.select();return}L(t.hits),l.value="",a*p<u&&v()}catch{n.error({title:"Error",message:"Something went wrong",position:"topRight"})}finally{setTimeout(()=>{b()},500)}});H.addEventListener("click",async()=>{a+=1,f(),w();try{const o=await h(c,a);L(o.hits);const{height:t}=document.querySelector(".gallery .gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),a*p>=u?n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):setTimeout(()=>{v()},500)}catch{n.error({title:"Error",message:"Something went wrong",position:"topRight"})}finally{setTimeout(()=>{b()},500)}});function O(o){if(o.length===0){n.warning({title:"Error",message:"Something went wrong"});return}renderGallery(o)}O(hits);a===1&&hits.length<=p&&(n.info({title:"Warning",message:"We're sorry, but you've reached the end of search results."}),f());
//# sourceMappingURL=index.js.map
